import Image from 'next/image'
import { checkAuthentication } from '../../api/auth';
import { redirect } from 'next/navigation';
import { cookies as cookie } from 'next/headers';

export const metadata = {
  title: 'About - Thintry',
  description: 'Generated by create next app',
}

export default async function About() {
  const cookies = cookie();
  let userLogged = await cookies.has('user');
  let isAuthenticated = await checkAuthentication('/about', userLogged);
  isAuthenticated ? '' : redirect('/auth/login');
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>About</h1>
    </main>
  )
}
