import Image from 'next/image';
import Link from 'next/link';

import { redirect } from 'next/navigation';
import SignupUi from '@/app/components/signup-ui/signupui';
import { cookies as cookie } from 'next/headers';

export const metadata = {
  title: 'Signup - Thintry',
  description: 'Generated by create next app',
}

export default async function Login() {
  const cookies = await cookie();
  let userLogged = await cookies.has('user-token');
  userLogged ? redirect('/profile') : console.log("Please Signup.") ;

  return (
    <div>
      <SignupUi />
    </div>
  )
}
