import Image from 'next/image'
import { checkAuthentication } from '../../api/auth';
import { redirect } from 'next/navigation';
import { cookies as cookie } from 'next/headers';
import HeaderUi from '../components/header-ui/headerui';
import FooterUi from '../components/footer-ui/footerui';

export const metadata = {
  title: 'Profile - Thintry',
  description: 'Generated by create next app',
}

export default async function Profile() {
  const cookies = cookie();
  let userLogged = await cookies.has('user');
  let isAuthenticated = await checkAuthentication('/profile', userLogged);
  isAuthenticated ? '' : redirect('/auth/login');
  return (
    <main>
      <HeaderUi />
      <FooterUi />
    </main>
  )
}
