import Image from 'next/image';
import Link from 'next/link';

import { redirect } from 'next/navigation';
import VerifyUi from '@/app/components/verify-ui/verifyui';
import { cookies as cookie } from 'next/headers';

export const metadata = {
  title: 'Verify - Thintry',
  description: 'Generated by create next app',
}

export default async function Verify() {
  const cookies = await cookie();
  let userLogged = await cookies.has('user-token');
  userLogged ? redirect('/profile') : '';

  return (
    <div>
      <VerifyUi />
    </div>
  )
}
